# Instructs the system model to re-initialize to a certain state.

float64[] state_vector          # The vector to set as the initial state.
float64[] state_covariance      # The row-major representation of the state's covariance matrix.

---

uint8 result                                    # Indicates the result of the operation.
uint8 RESULT_SUCCESS = 0                        # The state was re-initialized successfully.
uint8 RESULT_INVALID_VECTOR_SIZE = 1            # The provided state vector size does not match the number of states in the system model.
uint8 RESULT_INVALID_COVARIANCE_SIZE = 2        # The provided state covariance matrix dimensions do not match the number of states in the system model.